fs = require 'fs'
coffee_script = require 'coffee-script'
{extend} = require './lib/helpers'

task 'sbuild', 'build the CoffeeScript language from source', build = (cb) ->
  files = fs.readdirSync 'src'
  for file in files
    data = coffee_script.compile fs.readFileSync('src/' + file, 'utf8')
    fs.writeFile(
      'lib/' + file.replace(/\.coffee$/, '.js'),
      data,
      (err) -> console.log err if err
    )

task 'build:parser', 'rebuild the Jison parser (run build first)', ->
  require 'jison'
  extend global, require('util')
  parser = require('./lib/grammar').parser
  fs.writeFile 'lib/parser.js', parser.generate()