fs = require 'fs'
coffee_script  = require 'coffee-script'

task 'sbuild', 'build the CoffeeScript language from source', build = (cb) ->
  files = fs.readdirSync 'src'
  for file in files
    data = coffee_script.compile fs.readFileSync('src/' + file, 'utf8')
    console.log file
    fs.writeFile(
      'lib/' + file.replace(/\.coffee$/, '.js'),
      data,
      (err) -> console.log err if err
    )

task 'build:parser', 'rebuild the Jison parser (run build first)', ->
  extend global, require('util')
  require 'jison'
  parser = require('./lib/coffee-script/grammar').parser
  fs.writeFile 'lib/coffee-script/parser.js', parser.generate()